cabecas:
  jogadores:
    ativado: true
    chance: 25.0
    nome: "&fCabeça de %player%"
    lore:
      - ""
      - "&7Pertenceu a &f%player%&7."
      - ""

  mobs-e-animais: true
  chance-mobs-e-animais: 10.0

mensagens:
  recarregado: "&a&lᴄᴏᴍʙᴀᴛᴇᴘʟᴜs &8• &aConfiguração recarregada."
  sem-permissao: "&c&lᴄᴏᴍʙᴀᴛᴇᴘʟᴜs &8• &cVocê não tem permissão."
  uso: "&e&lᴄᴏᴍʙᴀᴛᴇᴘʟᴜs &8• &fUse: &7/combateplus reload"
