name: CombatePlus
version: '1.0.0'
main: com.donnie1337.combateplus.CombatePlus
api-version: '26.2'
author: donnie1337
description: Sistema de combate e cabeças da rede.

commands:
  combateplus:
    description: Administração do CombatePlus.
    usage: /combateplus reload
    aliases:
      - cplus
    permission: combateplus.admin
  pvp:
    description: Ativa ou desativa o PvP do jogador.
    usage: /pvp
  head:
    description: Obtém uma cabeça de mob ou animal.
    usage: /head <mob>
    aliases:
      - cabeca
      - cabeça
    permission: combateplus.head

permissions:
  combateplus.admin:
    description: Permite administrar o CombatePlus.
    default: op
  combateplus.head:
    description: Permite obter cabeças de mobs e animais.
    default: op
